version: '3'

services: 
  docker-mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=testdb
      - MYSQL_PASSWORD=root
  spring-boot-jpa-docker-webapp:
    image: demoapp
    depends_on:
      - docker-mysql
    ports:
      - 8080:8080
    environment:
      - DOCKER_MYSQL_DB_HOST=demoapp_docker-mysql_1
      - DOCKER_MYSQL_DB_PORT=3306
      - DOCKER_DB_USERNAME=dilshob
      - DOCKER_DB_PASSWORD=root
     